"""added database model and schemas for booking

Revision ID: 2b53e7e3cb8d
Revises: 53aeedddcad1
Create Date: 2024-10-22 22:34:07.359409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b53e7e3cb8d'
down_revision: Union[str, None] = '53aeedddcad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
