"""added email field to the User model

Revision ID: 53aeedddcad1
Revises: 32bfd9d66e3c
Create Date: 2024-10-22 15:00:39.523791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53aeedddcad1'
down_revision: Union[str, None] = '32bfd9d66e3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'email')
    # ### end Alembic commands ###
